### PR TITLE
Added the Whitespace style where the separator is a single whitespace

### PR DESCRIPTION
**Pull request by wargamer**
As requested by issue #61

### CODE REVIEW

**Comment by tdwright** [comment]
HI @wargamer!

Thanks for this PR. From a superficial look, everything looks fine. I see you've added a new conformance test to go with the new style, which is great. I'll go through it all properly this weekend when I'm in front of my laptop.

The only thing that I'm not sure about is the name. I was going to raise this on the issue (#61) itself, but you were too quick with this PR! 😉 "Empty" is what the reporting user initially suggested, but I'm not sure it's quite right. To me it feels like it almost implies there will be no data in the table. What do you think? Some ideas I had were:

- Whitespace
- Blanks
- Gaps
- Ghost

I'm also open to any suggestions you (or others?) might have. Or, if you really like "Empty", we can stick with that.

Tom

**Comment by wargamer** [comment]
Hi Tom,

You make a fair point, hadn't thought of it that way.
I went with Whitespace since that seems most descriptive/fitting out of the four.

**Comment by tdwright** [comment]
Ah brilliant. I personally think that name works loads better. And thanks for the quick turnaround.

I'll get this properly reviewed ASAP, but (like I said) it'll probably be over the weekend whilst I'm working on #60 

Cheers,
Tom

**Review by tdwright — APPROVED** [review]
All good! 💯 

Thanks for your contribution @wargamer!

**Pull request merged**
