### PR TITLE
Removed locale dependency from tests

### PR DESCRIPTION
**Pull request by zumo-sk**
-Fixed 20 tests to use detected decimal separator instead of hard-coded
-Added 2 tests to test currency formatting for decimal comma and decimal point
First attempt to participate in open source, so please have mercy! 😄

### CODE REVIEW

**Review by tdwright — CHANGES_REQUESTED** [review]
Hi @zumo-sk,

Have looked at this properly and want to thank you again for taking the time to help tighten up these tests. 😁 

It looks like you've used three different approaches in these tests:

1. For some of them, you're relaxing the expected value to match whatever the current culture will do. Specifically, you've changed the `.` to `NumberFormat.NumberDecimalSeparator`.
2. For others, you're specifying the culture (using `Thread.CurrentThread.CurrentCulture`) that the thread should use, then hard-coding the expected value.
3. For some of the dates, you're supplying the format string, so localisation doesn't come into play at all.

After some reflection, I think my preference is for number 2. Because the results are so visual, I think having variable names inlined hurts readability. If we consistently took the approach of explicitly specifying the culture for these tests (as you've done in some instances), we'd be able to avoid this.

The other suggestion I'd make would be to change some of these tests from `[Test]` to [`[TestCase]`](https://github.com/nunit/docs/wiki/TestCase-Attribute). The tests of `StringValForCol()` would be great candidates for this, as you could do something like this:

```C#
[TestCase("yyyy-MM-dd","2018-12-31")]
[TestCase("dd.MM.yy","31.12.18")]
public void DateTimeFieldCanBeFormatted(string format, string expected)
{
        // Arrange
        var tableObj = Table<TestDataType>.Create();
        // Act
        tableObj.Columns[3].FormatString = format;
        var val = tableObj.Columns[3].StringValForCol(new DateTime(2018, 12, 31));
        // Assert
        val.ShouldBe(expected);
}
```
Maybe give that a go and see if it helps cut down some repitition.

Anyway, this is a great first pull request with the potential to be a very good merge. Sorry to bump it back to you with these suggestions, but I promise it'll be worth it! 👍 

Thanks again,
Tom

**Comment by zumo-sk** [comment]
Hi Tom,

Thanks for the comments. I joined the project not just to help the community, but also to learn good practices, so thanks for valuable review comments. I tried to push the rework one step further - I hope you will agree the new date format test is a good unification of what we tried to achieve - to test both formatting and how it depends on the system locale settings.
Please review again when you are going to have time and no worries - if you don't like something, just let me know and I'll try to work on it further. 😅

Marek

**Comment by zumo-sk** [comment]
Hi Tom,

It seems that if you use slashes in a format, it uses then the culturally
defined decimal separators, like described here:
https://stackoverflow.com/a/31185798
So I included that in the test. If you find it useless, I can remove it,
but I had to give it a try. :smile:
If I remember correctly, in the Slovak culture settings, I am using
"d/M/yyyy" to have "31.1.2018" - so the "d" format is being tested (I tried
to use formats that are really being used in those countries). But using
weird formats like "dddd" sounds like a good and fun thing to do. :) I'll
add new formats later this week when I'm going to have time, let me know if
you agree that the cultural test to test date separators is a good idea.
Thanks,

Marek

**Comment by tdwright** [comment]
Well, I did not know that about the slashes... Very interesting! 💡 (Another great thing about open source projects!)

In that case I'd be happy to accept this PR as it is. If you'd like me to hold off so you can add more tests, just let me know.

Tom

**Review by tdwright — APPROVED** [review]

**Comment by zumo-sk** [comment]
I was thinking about it and I guess I am happy with the tests as they are. Thank you and if you haven't changed your mind, feel free to merge it. Hooray, first real open source participation! 😅

**Comment by tdwright** [comment]
@zumo-sk Thanks for your contribution!

**Pull request merged**
